var slideInc=0.5,slideBase=-0.5,slideSpeed,slideInterval=10,currentPage=c=null,currentDialog=null,currentWidth=0,currentYOffset=0,currentHash=location.hash,activeLi,hashPrefix="#_",pageHistory=[],pageLocationHistory=[],currentLocation=1,preSelect=null,newPageCount=0,checkTimer,activepicload=!1,multiselect=!1,usercontrol=[],wdlg,btnfrm,tse=[],tee=[],kbar,kform,remotewin,remotevol=null,touchDevice=isTouchDevice();
function isTouchDevice(){try{return document.createEvent("TouchEvent"),!0}catch(a){return!1}}
window.iui={showPage:function(a,b){if(a)if(currentDialog&&(currentDialog.removeAttribute("selected"),currentDialog=null),hasClass(a,"dialog"))showDialog(a);else{var d=currentPage;currentPage=a;d?setTimeout(slidePages,0,d,a,b):updatePage(a,d)}},showPageById:function(a,b){var d=$(a);if(d){var e=pageHistory.indexOf(a),g=e!=-1||b;g&&pageHistory.splice(e,pageHistory.length);iui.showPage(d,g)}},showPageByHref:function(a,b,d,e,g){e||waitDialog(!0);var f=new XMLHttpRequest;f.onerror=function(){g&&g(!1)};
f.onreadystatechange=function(){if(f.readyState==4){if(e)replaceElementWithSource(e,f.responseText);else{var a=document.createElement("div");a.innerHTML=f.responseText;iui.insertPages(a.childNodes)}g&&setTimeout(g,1E3,!0);waitDialog(!1)}};b?(d=="POST"?f.open(d,a,!0):f.open(d,a+"?"+b.join("&"),!0),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.setRequestHeader("Content-Length",b.length),f.send(b.join("&"))):(f.open(d||"GET",a,!0),f.send(null))},showPageByHash:function(a,b){var d=
$(a);d.setAttribute("selected","true");iui.showPage(d,b);setTimeout(d.removeAttribute("selected"),500)},insertPages:function(a){for(var b,d=0;d<a.length;++d){var e=a[d];if(e.nodeType==1){if(!e.id)e.id="__"+ ++newPageCount+"__";var g=$(e.id);g?g.parentNode.replaceChild(e,g):document.body.appendChild(e);if(e.getAttribute("selected")=="true"||!b)b=e;--d}}b&&iui.showPage(b)},getSelectedPage:function(){for(var a=document.body.firstChild;a;a=a.nextSibling)if(a.nodeType==1&&a.getAttribute("selected")=="true")return a},
getPrePages:function(){for(var a=[],b=document.body.firstChild;b;b=b.nextSibling)b.nodeType==1&&b.getAttribute("selected")=="pre"&&(b.removeAttribute("selected"),a.push(b.id));return a},refreshPage:function(){waitDialog(!0);(page=iui.getSelectedPage())&&iui.showPageByHref(page.getAttribute("tag"))}};
addEventListener("load",function(){var a=iui.getPrePages();if(a)for(var b=1,d=0;d<a.length;++d)pageHistory.splice(pageHistory.length-b--,0,a[d]),pageLocationHistory.splice(pageHistory.length-b--,0,1),location.hash=hashPrefix+a[d],scrollTo(0,1);(a=iui.getSelectedPage())&&iui.showPage(a);setTimeout(preloadImages,0);setTimeout(checkOrientAndLocation,0);checkTimer=setInterval(checkOrientAndLocation,300);setTimeout(scrollTo,100,0,1)},!1);
addEventListener("click",function(a){var b=findParent(a.target,"a");if(b){currentLocation=window.pageYOffset;var d=function(){b.removeAttribute("selected")};if(b.href&&b.hash&&b.hash!="#")b.setAttribute("selected","true"),iui.showPage($(b.hash.substr(1))),setTimeout(d,500);else if(b==$("backButton"))history.back();else if(b.getAttribute("type")=="submit")submitForm(findParent(b,"form"));else if(b.getAttribute("type")=="cancel")cancelDialog(findParent(b,"form"));else if(b.target=="_replace")b.setAttribute("selected",
"progress"),iui.showPageByHref(b.href,null,null,b,d);else if(b.target=="_js")doJSByHref(b.href);else if(!b.target&&b.href)b.setAttribute("selected","progress"),iui.showPageByHref(b.href,null,null,null,d);else return;a.preventDefault()}},!0);addEventListener("click",function(a){var b=findParent(a.target,"div");b&&hasClass(b,"toggle")&&(b.setAttribute("toggled",b.getAttribute("toggled")!="true"),a.preventDefault())},!0);
addEventListener("click",function(a){(a=findParent(a.target,"li"))&&(activeLi=a)},!0);
function loadPictures(a){if(activepicload)return!0;else activepicload=!0;if(!currentPage)return!1;if(!currentPage.getAttribute("afterPictures"))return!1;for(var b in currentPage.childNodes){var d=currentPage.childNodes[b];if(d.nodeName=="LI"){var e=d.getAttribute("afterPicture");if(e){var g=currentPage.offsetTop+d.offsetTop;if(g>window.pageYOffset+window.innerHeight&&a)break;if(!(g+d.height<window.pageYOffset&&a))d.getElementsByTagName("img")[0].src=e,d.removeAttribute("afterPicture")}}}return!1}
function checkOrientAndLocation(){if(window.innerWidth!=currentWidth)currentWidth=window.innerWidth,currentPage.getAttribute("scroll")&&createScrollBar(currentPage);if(currentYOffset!=window.pageYOffset)currentYOffset=window.pageYOffset,touchDevice&&(activepicload=loadPictures(touchDevice));if(decodeURI(location.hash)!=currentHash){var a=location.hash.substr(hashPrefix.length);iui.showPageById(a,location.hash=="#_main")}}
function showDialog(a){currentDialog=a;window.pageYOffset<1&&window.scrollTo(0,1);a.style.top=window.pageYOffset+"px";a.style.height=Math.min(window.innerHeight,500)+"px";a.setAttribute("selected","true");hasClass(a,"dialog")&&!a.target&&showForm(a)}function showForm(a){a.onsubmit=function(b){b.preventDefault();submitForm(a)};a.onclick=function(b){b.target==a&&hasClass(a,"dialog")&&cancelDialog(a)}}function cancelDialog(a){a.removeAttribute("selected")}
function updatePage(a,b,d,e){if(!a.id)a.id="__"+ ++newPageCount+"__";location.href=currentHash=hashPrefix+a.id;e||pageHistory.push(a.id);pageHistory.length>2?$("backicon").style.display="inline":$("backicon").style.display="none";a.id!="main"&&d&&setTimeout(scrollTo,300,0,d);b=$("pageTitle");if(a.title)b.innerHTML=a.title;a.localName.toLowerCase()=="form"&&!a.target&&showForm(a);if(b=$("backButton"))(d=$(pageHistory[pageHistory.length-2]))&&!a.getAttribute("hideBackButton")?(b.style.display="inline",
b.innerHTML=d.title?d.title:"Back"):b.style.display="none";a.getAttribute("scroll")&&createScrollBar(a);a.getAttribute("dynamicnode")&&updateNodes(a);kb().style.height=document.height+"px";activepicload=loadPictures(touchDevice)}function updateNodes(a){var a=a.getAttribute("dynamicnode").split(/ /),b;for(b in a)$(a[b])&&$(a[b]).getAttribute("tag")&&iui.showPageByHref($(a[b]).getAttribute("tag"),null,null,$(a[b]))}
function createScrollBar(a){var b,d,e=[],g=0,f=a.getAttribute("scroll").toLowerCase()=="view",h;for(h in currentPage.childNodes)if(currentPage.childNodes[h].id=="scrollBar"&&(b=currentPage.childNodes[h]),currentPage.childNodes[h].id=="scrollBarText"&&(d=currentPage.childNodes[h]),b&&d)break;for(var j in currentPage.childNodes)h=currentPage.childNodes[j],(h.nodeName=="LI"||h.nodeName=="H2")&&h.id&&e.push(h);if(!(e.length<2)){if(!d){d=document.createElement("div");d.id="scrollBarText";d.style.display=
"none";j=[];for(var i in e)j.push(e[i].title||e[i].id);d.innerHTML=j.join("<br>");a.appendChild(d)}d.style.height=window.innerHeight+"px";d.style.fontSize=Math.min(22,Math.max(9,(window.innerHeight-e.length*3)/e.length))+"px";d.style.lineHeight=window.innerHeight/e.length+"px";if(!b)b=document.createElement("div"),b.id="scrollBar",a.appendChild(b);f&&(b.addEventListener("touchstart",function(){d.style.display="block";d.style.top=window.pageYOffset-45+"px"},!1),b.addEventListener("touchend",function(){d.style.display=
"none"},!1));b.addEventListener("touchmove",function(a){a.preventDefault()},!1);b.addEventListener("touchmove",function(b){b=Math.floor((b.targetTouches[0].pageY-window.pageYOffset)/(Math.floor(window.innerHeight/e.length)*e.length/e.length));if(g!=b&&b>=0&&b<e.length){g=b;b=Math.min(a.offsetHeight-window.innerHeight,e[b].offsetTop);if(f)d.style.top=b+"px";window.scrollTo(0,b+45)}},!1)}}
function clonePage(a,b){var d=a.cloneNode(!0);d.style.position="absolute";d.style.left=b;d.style.top=a.offsetTop+"px";d.style.width="100%";d.setAttribute("selected","true");document.body.appendChild(d);return d}
function slidePages(a,b,d){d?(d=pageLocationHistory[pageLocationHistory.length-1],pageLocationHistory.pop(),Slide?slidePagesGauche(a,b,d):(b.setAttribute("selected","true"),a.removeAttribute("selected"),setTimeout(updatePage,100,b,a,d)),a&&(b=a.getAttribute("temporary"))&&b.toLowerCase()=="yes"&&a.parentNode.removeChild(a)):b.id!=a.id?(pageLocationHistory.push(window.pageYOffset),Slide?slidePagesDroite(a,b):(b.setAttribute("selected","true"),a.removeAttribute("selected"),setTimeout(updatePage,100,
b,a,1,b.id==a.id))):(b.setAttribute("selected","true"),a.removeAttribute("selected"),setTimeout(updatePage,100,b,a,currentLocation,b.id==a.id))}
function slidePagesDroite(a,b){var d=window.innerWidth;b.style.left="100%";b.setAttribute("selected","true");scrollTo(0,1);clearInterval(checkTimer);var e=100;slideSpeed=slideBase;var g=setInterval(function(){e>=33?slideSpeed+=slideInc:(slideSpeed-=1.6*slideInc,slideSpeed<=1&&(slideSpeed=1));e-=slideSpeed;if(e<=0){e=0;clearInterval(g);scrollTo((100-e)/100*d,1);a.removeAttribute("selected");var f=clonePage(b,d+"px");b.style.left="0px";var h=0,j=setInterval(function(){h>0&&(scrollTo(0,1),document.body.removeChild(f),
clearInterval(j));h++},10);checkTimer=setInterval(checkOrientAndLocation,300);setTimeout(updatePage,0,b,a)}else scrollTo((100-e)/100*d,1)},slideInterval)}
function slidePagesGauche(a,b,d){var e=window.innerWidth,g=clonePage(a,e+"px");scrollTo(e,1);b.style.left="0px";b.setAttribute("selected","true");document.body.removeChild(a);clearInterval(checkTimer);var f=100;slideSpeed=slideBase;var h=setInterval(function(){f>=33?slideSpeed+=slideInc:(slideSpeed-=1.6*slideInc,slideSpeed<=1&&(slideSpeed=1));slideSpeed==0.0020&&(slideSpeed=3);slideSpeed==0.0010&&(slideSpeed=0.0020);slideSpeed==1.5&&(slideSpeed=0.0010);f-=slideSpeed;f<=0&&(f=0,clearInterval(h),scrollTo(f/
100*e,1),g.removeAttribute("selected"),checkTimer=setInterval(checkOrientAndLocation,300),setTimeout(updatePage,0,b,a,d));scrollTo(e*f/100,1)},slideInterval)}function preloadImages(){var a=document.createElement("div");a.id="preloader";document.body.appendChild(a)}function submitForm(a){iui.showPageByHref(a.action||"POST",encodeForm(a),a.method)}
function encodeForm(a){function b(a){for(var b=0;b<a.length;++b){var f=a[b];if(f.name)if(f.getAttribute("multiple")!=null)for(var h=0;h<f.length;++h)f[h].selected&&(utf8?d.push(f.name+"="+encodeURI(f[h].value)):d.push(f.name+"="+escape(f[h].value)));else utf8?d.push(f.name+"="+encodeURI(f.value)):d.push(f.name+"="+escape(f.value))}}var d=[];b(a.getElementsByTagName("input"));b(a.getElementsByTagName("select"));return d}
function findParent(a,b){for(;a&&(a.nodeType!=1||a.localName.toLowerCase()!=b);)a=a.parentNode;return a}function hasClass(a,b){return a.className.match(RegExp("(\\s|^)"+b+"(\\s|$)"))}function addClass(a,b){this.hasClass(a,b)||(a.className+=" "+b)}function removeClass(a,b){if(hasClass(a,b))a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," ")}
function replaceElementWithSource(a,b){for(var d=a.parentNode,e=a;d.parentNode!=document.body;)d=d.parentNode,e=e.parentNode;var g=document.createElement(e.localName);for(g.innerHTML=b;g.firstChild;)d.insertBefore(g.firstChild,e);d.removeChild(e)}function $(a){return document.getElementById(a)}function ddd(){console.log.apply(console,arguments)}function bf(){btnfrm||(btnfrm=$("buttonsForm"));return btnfrm}function wd(){wdlg||(wdlg=$("dlg_wait"));return wdlg}
function kb(){kbar||(kbar=$("keyBar"));return kbar}function kf(){kform||(kform=$("keysform"));return kform}function isObject(a){return a&&"object"==typeof a}function isArray(a){return isObject(a)&&a.constructor==Array}function toggle(a,b,d,e){if(a.getAttribute("id"))for(var g in a.childNodes)if(b=a.childNodes[g],typeof a.childNodes[g]=="object"&&b&&b.getAttribute("type")=="hidden")b.value=a.getAttribute("toggled")=="true"?d:e}
function toggleDiv(a,b){a.getAttribute("id")&&b&&(a.getAttribute("toggled")=="true"?showElement(b):hideElement(b))}function fillElementByHref(a,b,d){var e=new XMLHttpRequest;e.onreadystatechange=function(){if(e.readyState==4)b.innerHTML=e.responseText,d&&d(!0)};e.open("GET",a,!0);e.send(null)}function doJSByHref(a,b){waitDialog(!0);var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState==4&&(eval(d.responseText),b&&b(!0),waitDialog(!1))};d.open("GET",a,!0);d.send(null)}
function SimpleHttpRequest(){for(var a=0;a<SimpleHttpRequest.arguments.length;++a){var b=new XMLHttpRequest;b.open("GET",SimpleHttpRequest.arguments[a],!0);b.send(null)}}function hideElement(a){$(a).style.display="none"}function showElement(a){$(a).style.display="block"}function deleteHistory(a){pageHistory=[];pageLocationHistory=[];if(a)clearInterval(checkTimer),currentPage.removeAttribute("selected"),currentPage=$(a),currentHash=hashPrefix+a,location.hash=hashPrefix+a,pageHistory=[a]}
function unCheck(){for(var a=document.getElementsByName("record"),b=0;b<a.length;++b)a[b].getAttribute("checked")&&a[b].removeAttribute("checked"),a[b].style.backgroundColor=""}
function recBar(a){for(var b in document.getElementsByName("recoptiontoggle"))if(b<document.getElementsByName("recoptiontoggle").length)document.getElementsByName("recoptiontoggle")[b].style.display=a?"none":"block";for(var d in document.getElementsByName("recoption"))if(d<document.getElementsByName("recoptiontoggle").length)document.getElementsByName("recoption")[d].style.display=a?"block":"none"}
function button(a,b,d,e,g,f){this.value=a;this.href=b;this.onclick=d;this.question=e;this.target=g;this.image=f}
function dialog(a,b,d,e,g,f){function h(a){$("btnsarea").innerHTML="";if(a.activePageNo==1)a=f;else var b=(a.activePageNo-1)*8,a=[f[b],f[++b],f[++b],f[++b]];for(b=0;b<=a.length-1;b++){var d=document.createElement("a");d.className="dialogbutton";d=$("btnsarea").appendChild(d);a[b]?(d.innerHTML="<img src='"+a[b].image+"' /><br>"+a[b].value,a[b].href?d.setAttribute("href",encodeURI(a[b].href)):d.removeAttribute("href"),a[b].target?d.setAttribute("target",a[b].target):d.removeAttribute("target"),a[b].onclick?
d.setAttribute("onclick",a[b].question?'if(confirm("'+a[b].question+'")) {'+a[b].onclick+"}":a[b].onclick):d.removeAttribute("onclick")):d.style.display="none"}}this.activePageNo=1;this.toggle=function(){this.activePageNo*4>=f.length?this.activePageNo=1:this.activePageNo+=1;h(this)};this.show=function(){var e=bf();$("headline").innerHTML=a;$("morebtn").style.display="none";$("selectField").style.display="none";$("epginfobar").style.display="none";$("moviebtn").style.display="none";$("toprightbtn").style.display=
"none";$("epginfobar").innerHTML="";$("timebardiv").style.display="none";if(f.length>100)$("morebtn").style.display="block";b?$("recbtns").style.display="block":$("recbtns").style.display="none";d?$("cntrlbtns").style.display="block":$("cntrlbtns").style.display="none";if(g!=null)if(g[0]!=null){$("moviebtn").style.height="110px";$("rateStars").style.display="block";var i=$("rateStars").childNodes,k;for(k in i)if(i[k].nodeType==1&&i[k].getAttribute("tag")!=null)i[k].onclick=new Function("dialogStars(this.getAttribute('tag'), '"+
g[1]+"');");dialogStars(g[0])}else $("rateStars").style.display="none",$("moviebtn").style.height="210px";else $("rateStars").style.display="none",$("moviebtn").style.height="210px";h(this);showDialog(e)}}var oDialog;
function epgDialog(a,b,d,e,g){e=[mpplay?new button(lp_SWITCH,ivdr+"?cmdat+"+g+"+CHAN+"+a+"|MESG+iVDR SWITCH: "+d,"cancelDialog(bf());",null,"_js",www+"/btn_start.png"):new button(lp_PLAY,ivdr+"?mpplay+CHAN+"+a,null,null,"_js",www+"/btn_start.png"),b!="NOEPG"?new button(lp_REPLAY,ivdr+"?REPLAY+"+a+"+"+b,null,null,null,www+"/btn_search.png"):null,b!="NOEPG"?new button(lp_RECORD,null,"var dir = prompt('"+lp_PREFIX+"','"+recprefix+"'); if (dir != null) {cancelDialog(bf()); doJSByHref('"+ivdr+"?NEWTIMER+"+
a+"+"+b+"+'+dir, iui.refreshPage)}",null,null,www+"/btn_save.png"):null,e=="NOW"?stream&&new button(lp_STREAM,null,"$('btnsarea').innerHTML = ''; if (confirm('"+lp_STARTNOW+"')) doJSByHref(ivdr+'?stream=dialog&type=live&id="+a+"'); else doJSByHref(ivdr+'?stream=live&id="+a+"');",null,null,www+"/btn_show.png"):null,b!="NOEPG"?new button("epgSearch",ivdr+"?EPGSEARCHFIELD+new+"+d+"+"+a,null,null,"_changewindow",www+"/btn_epgs.png"):null,e!="SCHED"?new button(lp_SCHED,ivdr+"?CHANINFO+"+a,null,null,null,
www+"/btn_sched.png"):null,b!="NOEPG"?new button(lp_INFO,null,'$("epginfobar").style.display = "block"',null,null,www+"/btn_info.png"):null];for(g=0;g<usercontrol.length;g++)e.push(usercontrol[g]);oDialog=new dialog(d,null,null,null,null,e);oDialog.show();fillElementByHref(ivdr+"?EPGINFOFIELD+"+a+"+"+b+"+1",$("epginfobar"))}
function recDialog(a,b,d,e,g,f){if(multiselect)d.getAttribute("checked")?(d.style.backgroundColor="",d.removeAttribute("checked")):(d.style.backgroundColor="#D0E0FF",d.setAttribute("checked","true"));else{b=[mpplay?new button(lp_BEGIN,ivdr+"?cmd+PLAY+"+a+"+begin",null,null,null,www+"/btn_start.png"):null,mpplay?new button(lp_RESUME,ivdr+"?cmd+PLAY+"+a,null,null,null,www+"/btn_play.png"):new button(lp_PLAY,ivdr+"?mpplay+REC+"+a,null,null,null,www+"/btn_start.png"),stream&&new button(lp_STREAM,null,
"$('btnsarea').innerHTML = ''; if (confirm('"+lp_STARTNOW+"')) doJSByHref(ivdr+'?stream=dialog&type=rec&id="+a+"'); else doJSByHref(ivdr+'?stream=rec&id="+a+"');",null,null,www+"/btn_show.png"),new button(lp_REPLAY,ivdr+"?REPLAY+"+a,null,null,null,www+"/btn_search.png"),new button(lp_RENAME,null,"var name = prompt('"+lp_RENAME+"', '"+e+"'); if (name) { iui.showPageByHref('"+ivdr+"?REC=RENR&hs="+b+"&st="+g+"&sq="+f+"&ID="+a+"&STRING='+name); }",null,null,www+"/btn_edit.png"),new button(lp_MOVE,ivdr+
"?MOVE+"+a,null,null,"_js",www+"/btn_folder.png"),new button(lp_REMOVE,null,"cancelDialog(bf()); unCheck(); iui.showPageByHref('"+ivdr+"?REC=DELM&IDS="+a+"&hs="+b+"&st="+g+"&sq="+f+"')",lp_DELREC,null,www+"/btn_trash.png"),new button(lp_INFO,null,'$("epginfobar").style.display = "block"',null,null,www+"/btn_info.png")];for(d=0;d<usercontrol.length;d++)b.push(usercontrol[d]);oDialog=new dialog(e||lp_RECORDS,!0,null,null,null,b);oDialog.show();fillElementByHref(ivdr+"?RECINFOFIELD+"+a+"+1",$("epginfobar"))}}
function timDialog(a,b,d){for(var a=[new button(lp_ON+"/"+lp_OFF,null,"cancelDialog(bf()); iui.showPageByHref('"+ivdr+"?TIMER+ONOFF+"+a+"');",null,null,www+"/btn_switch.png"),new button(lp_EDIT,ivdr+"?TINFO+"+a+"+Bearbeiten",null,null,"_changewindow",www+"/btn_edit.png"),b!="NOEPG"?new button(lp_REPLAY,ivdr+"?REPLAY+"+b+"+"+d,null,null,null,www+"/btn_search.png"):null,new button(lp_REMOVE,null,"cancelDialog(bf()); iui.showPageByHref('"+ivdr+"?TIMER+DELT+"+a+"')",lp_DELTIMER,null,www+"/btn_trash.png")],
e=0;e<usercontrol.length;e++)a.push(usercontrol[e]);oDialog=new dialog(lp_TIMER,null,null,new button(lp_INFO,null,'$("epginfobar").style.display = "block"'),null,a);oDialog.show();fillElementByHref(ivdr+"?EPGINFOFIELD+"+b+"+"+d+"+1",$("epginfobar"))}
function espDialog(a,b){for(var d=[new button(lp_ON+"/"+lp_OFF,null,"cancelDialog(bf()); iui.showPageByHref('"+ivdr+"?EPGSEARCH+ONOFF+"+a+"');",null,null,www+"/btn_switch.png"),new button(lp_EDIT,ivdr+"?EPGSEARCHFIELD+"+a+"+Bearbeiten",null,null,"_changewindow",www+"/btn_edit.png"),new button(lp_DOSEARCH,ivdr+"?SEARCHRESULT+"+a,null,null,null,www+"/btn_search.png"),new button(lp_REMOVE,null,"cancelDialog(bf()); iui.showPageByHref('"+ivdr+"?EPGSEARCH+DELS+"+a+"')",lp_DELSEARCH,null,www+"/btn_trash.png")],
e=0;e<usercontrol.length;e++)d.push(usercontrol[e]);oDialog=new dialog(b,null,null,null,null,d);oDialog.show()}
function chaDialog(a,b){for(var d=[mpplay?new button(lp_SWITCH,ivdr+"?cmd+CHAN+"+a,"cancelDialog(bf());",null,null,www+"/btn_start.png"):new button(lp_PLAY,ivdr+"?mpplay+CHAN+"+a,null,null,"_js",www+"/btn_start.png"),new button(lp_SCHED,ivdr+"?CHANINFO+"+a+"+"+b,null,null,null,www+"/btn_sched.png"),stream&&new button(lp_STREAM,null,"$('btnsarea').innerHTML = ''; if (confirm('"+lp_STARTNOW+"')) doJSByHref(ivdr+'?stream=dialog&type=live&id="+a+"'); else doJSByHref(ivdr+'?stream=live&id="+a+"');",null,
null,www+"/btn_show.png"),new button(lp_RECORD,ivdr+"?TINFO+new+"+a+"+"+b,null,null,"_changewindow",www+"/btn_save.png")],e=0;e<usercontrol.length;e++)d.push(usercontrol[e]);oDialog=new dialog(b,null,null,null,null,d);oDialog.show()}
function mp3Dialog(a,b,d,e,g,f,h,j){var i="SimpleHttpRequest('"+sn;f&&(i="doJSByHref('"+ivdr+"?");var k,f=b;h&&(f=f.replace(/id/,"first"),$(h)||(h=currentPage));isArray(d)?d=i+d.join("'); "+i)+b+"'); ":d&&(d=i+d+b+"'); ");isArray(e)?(h&&(k=i+e.join("'); "+i)+"&"+h.getAttribute("all")+f+"'); "),e=i+e.join("'); "+i)+b+"'); "):e&&(h&&(k=i+e+"&"+h.getAttribute("all")+f+"'); "),e=i+e+b+"'); ");d=[h?new button(lp_ALLFRMHER,null,k+"; cancelDialog(bf())",null,null,www+"/btn_play.png"):e?new button(lp_PLAY,
null,e+"; cancelDialog(bf())",null,null,www+"/btn_start.png"):null,d&&new button(lp_ADD,null,d+"; cancelDialog(bf())",null,null,www+"/btn_add.png"),j&&new button(lp_MARK,null,"doJSByHref(ivdr+'?DATAMARKFILE+"+b+"'); cancelDialog(bf()); if (hasClass(activeLi, 'checked')) removeClass(activeLi, 'checked'); else addClass(activeLi, 'checked');",null,null,www+"/btn_mark.png"),stream&&new button(lp_STREAM,null,"$('btnsarea').innerHTML = ''; if (confirm('"+lp_STARTNOW+"')) doJSByHref(ivdr+'?stream=dialog&type=media&id="+
b+"'); else doJSByHref(ivdr+'?stream=media&id="+b+"');",null,null,www+"/btn_show.png"),new button(lp_OPEN,ivdr+"?media=play&file="+b,null,null,"_blank",www+"/btn_stream.png")];for(e=0;e<usercontrol.length;e++)d.push(usercontrol[e]);oDialog=new dialog(a,null,!0,new button(lp_INFO,null,'$("epginfobar").style.display = "block"; fillElementByHref("'+ivdr+"?database=infofield"+b+'", $("epginfobar"));'),[g,b],d);oDialog.show();$("moviebtn").src=ivdr+"?media=play&file="+b;$("moviebtn").style.display="block"}
function strDialog(a,b,d,e){for(var g=[new button(lp_SAVE,null,'cancelDialog(bf()); var name = prompt("'+lp_ENTERNAME+'", "'+a+'"); if (name) { doJSByHref(ivdr+"?stream=save&id='+d+'&name="+name) }',null,null,www+"/btn_save.png"),new button(lp_OFF,null,'cancelDialog(bf()); doJSByHref(ivdr+"?stream=stop&id='+d+'")',null,null,www+"/btn_switch.png"),new button(lp_REMOVE,null,'$("activemedia").style.display = "none"; cancelDialog(bf()); doJSByHref(ivdr+"?stream=remove&id='+d+'")',null,null,www+"/btn_cancel.png"),
new button(lp_OPEN,b+d+"/stream.m3u8",null,null,"_blank",www+"/btn_stream.png")],f=0;f<usercontrol.length;f++)g.push(usercontrol[f]);oDialog=new dialog(a,null,null,null,null,g);$("activemedia").style.display="block";$("activemedia").onclick=function(){strDialog(a,b,d,!0)};oDialog.show();if(!e)$("moviebtn").src=b+d+"/stream.m3u8";$("moviebtn").style.display="block"}function ivdrDialog(){showDialog(bf())}
function chooseButton(){var a=document.getElementsByName("multiSelectButton");if(multiselect){var b="";multiselect=!1}else b="act",multiselect=!0;for(var d=0;d<a.length;++d)a[d].className=b;if(!multiselect){a=document.getElementsByName("record");b=[];for(d=0;d<a.length;++d)a[d].getAttribute("checked")&&b.push(a[d].getAttribute("tag"));if(b.length>0){a=[new button(lp_REMOVE,null,"cancelDialog(bf()); deleteHistory('main'); unCheck(); iui.showPageByHref('"+ivdr+"?REC=DELM&IDS="+b.join("&IDS=")+"');",
b.length+" "+lp_MULTIDELETE,null,www+"/btn_trash.png"),null,new button(lp_MOVE,ivdr+"?MOVE+"+b.join("+"),null,null,"_js",www+"/btn_folder.png")];for(d=0;d<usercontrol.length;d++)a.push(usercontrol[d]);oDialog=new dialog(b.length+" "+lp_RECORDS,null,null,null,null,a);oDialog.show()}}}
function searchBarSet(a,b){var d=document.getElementsByName(b);if(a.className.match(/lightlightbgButton/))for(var e in a.className="inlinebutton",d)d[e].style.display="block";else for(e in a.className="inlinebutton lightlightbgButton",d)d[e].style.display="none"}function waitDialog(a,b){var d=wd(),e;e=b?b.top+b.height/2-34+"px":window.pageYOffset+window.innerHeight/2-34+"px";if(d)a?(d.style.display="block",d.style.top=e,d.style.left=window.innerWidth/2-34+"px"):d.style.display="none"}
function dialogStars(a,b){var d=$("rateStars").childNodes,e=0,g;for(g in d)if(d[g].nodeName=="SPAN")e++,d[g].className=a>=e?"ratestar":"ratedot";if(b&&(d=new XMLHttpRequest,d.open("GET",ivdr+"?database=write&"+b+"&data={IDS}{POPM}{URL}='iVDR'&data={IDS}{POPM}{Rating}="+(a==1?1:a==2?64:a==3?128:a==4?196:a==5?255:0),!0),d.send(null),$(b)))$(b).className="starspacer star"+a}
function pinmove(a){var a=typeof a=="undefined"?0:a?a.pageX-25:window.event.pageX-25,b=$("pin"),d=window.innerWidth-50,e=b.getAttribute("maxvalue"),d=parseInt(a/d*e);if(!(d<0||d>e))b.style.left=a-15+"px",b.setAttribute("value",d),b.innerHTML=parseInt(d/60)+":"+(d%60>9?"":"0")+parseInt(d%60)}function testme(a){var b,d;for(d in a)b+="\n"+d+" - "+a[d];alert(b)}function hitk(a,b,d){var a=[a,b,d],e;for(e in a)a[e]&&SimpleHttpRequest(keyparam+a[e])}
function moveFieldset(a,b){function d(a,b){for(a=a.previousSibling;a.nodeName!=b;)a=a.previousSibling;return a}function e(a,b){for(a=a.nextSibling;a.nodeName!=b;)a=a.nextSibling;return a}if(b){var g=e(a,"FIELDSET"),f=d(a,"H2");a.parentNode.insertBefore(a,f);a.parentNode.insertBefore(g,f)}else f=e(a,"H2"),g=e(f,"FIELDSET"),a.parentNode.insertBefore(f,a),a.parentNode.insertBefore(g,a)};
